version: "3.9"
services:
  daemon:
    image: ghcr.io/acces-sh/daemon:latest
    volumes:
      - "./authorized_keys:/app/authorized_keys/"
    environment:
      API_TOKEN: "YOUR_TOKEN"
  
  # Dev ENV Docker
  daemon-dev:
    build:
      context: ./
      dockerfile: ./Dockerfiles/multi/Dockerfile
    volumes:
      - "./authorized_keys:/app/authorized_keys"
    environment:
      API_TOKEN: "YOUR_TOKEN"
