version: "3.9"
services:
  # Dev Docker
  daemon:
    build:
      context: ./
      dockerfile: Dockerfile
      dockerfile: ./Dockerfiles/amd64/Dockerfile
    volumes:
      - "./authorized_keys:/app/authorized_keys"
    environment:
      API_TOKEN: "YOUR_TOKEN"
