name: 🚀 Daemon - Feature request
description: Suggest a feature 
title: "[Feature] :"
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
     Please [search for existing feature request](https://github.com/Acces-sh/daemon/issues) before creating a new one.
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
      required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
