blank_issues_enabled: true
contact_links:
  - name: Contact Acces.sh
    url: https://acces.sh/contact
    about: If you need any further info, feel free to get in touch and we will get back to you as soon as possible.
