name: Create release

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Version (ex 1.0.1)'
        required: true
        
jobs:        
  publish-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          
      - run: |
          bash build/build-debian.sh ${{ github.event.inputs.version }} linux-x64        
          bash build/build-debian.sh ${{ github.event.inputs.version }} linux-arm
          bash build/build-debian.sh ${{ github.event.inputs.version }} linux-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: |
            build/shdaemon_${{ github.event.inputs.version }}-1_amd64.deb
            build/shdaemon_${{ github.event.inputs.version }}-1_armhf.deb
            build/shdaemon_${{ github.event.inputs.version }}-1_arm64.deb
            install_script.sh
          body: Please refer to [CHANGELOG.md](https://github.com/Acces-sh/daemon) for details.
          token: ${{ secrets.CR_PAT }}
